# This is the OpenAPI specification for your service. It is used to generate the client code.
# To generate the server code, use the Gradle task `openApiGenerate`. The 
# generated code will be placed in `build/generate-resources/main`.
#
# We will evaluate you based on how well you design your API.
# 1. How well it follows REST principles.
# 2. How easy it is to understand and use.
#
# References
# 1. https://swagger.io/specification/
openapi: "3.0.0"
info:
  version: 1.0.0
  title: User Service
  license:
    name: MIT
servers:
  - url: http://localhost
paths:
  /register:
    post:
      summary: Endpoint to register user
      operationId: register
      parameters:
        - name: phone_number
          in: body
          required: true
          schema:
            type: string
        - name: password
          in: body
          required: true
          schema:
            type: string
        - name: full_name
          in: body
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:    
              schema:
                $ref: ""
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /login:
    put:
      summary: Endpoint for user login
      operationId: login
      parameters:
        - name: phone_number
          in: body
          required: true
          schema:
            type: string
        - name: password
          in: body
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:    
              schema:
                $ref: ""
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /profile:
    get:
      summary: Endpoint to get my profile
      operationId: get_profile
      parameters:
        - name: authorization
          in: header
          required: true
          schema:
            type: JWT
      responses:
        '200':
          description: Success
          content:
            application/json:    
              schema:
                $ref: ""
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /profile:
    put:
      summary: Endpoint to update my profile
      operationId: update_profile
      parameters:
        - name: phone_number
          in: body
          required: false
          schema:
            type: string
        - name: full_name
          in: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:    
              schema:
                $ref: ""
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    RegistrationParam:
      type: object
      required:
        - phone_number
        - full_name
        - password
      properties:
        phone_number:
          type: string
        full_name:
          type: string
        password:
          type: string
    LoginParam:
      type: object
      required:
        - phone_number
        - password
      properties:
        phone_number:
          type: string
        password:
          type: string
    UserData:
      type: object
      required:
        - phone_number
        - full_name
      properties:
        phone_number:
          type: string
        password:
          type: full_name
    UpdateProfileParam:
      type: object
      required:
        - phone_number
        - full_name
      properties:
        phone_number:
          type: string
        password:
          type: full_name
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
